name: todo_app
description: A new Flutter project.

publish_to: 'none' # Prevent publishing to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.14.0
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^4.7.0    # Jika Anda membutuhkan autentikasi Firebase

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true